export const ROUTES = {
  HOME: '/',
  PORTAL: '/portal',
  LOGIN: '/login',
  TICKETS_OPEN: '/{messageBoxId}/tickets/open/p1',
  TICKETS_PENDING: '/{messageBoxId}/tickets/pending/p1',
  TICKETS_REASON: '/{messageBoxId}/tickets/reason/{reasonId}/p1',
  TICKETS_CLOSED: '/{messageBoxId}/tickets/closed/p1',
  TICKETS_UNWANTED: '/{messageBoxId}/tickets/unwanted/p1',
  TICKETS_ALL: '/{messageBoxId}/tickets/all/p1',
  TICKETS_SENT: '/{messageBoxId}/tickets/sent/p1',
  TICKETS_SCHEDULED: '/{messageBoxId}/tickets/scheduled/p1',
  TICKETS_DRAFT: '/{messageBoxId}/tickets/draft/p1',
  TICKETS_SPAM: '/{messageBoxId}/tickets/spam/p1',
  TICKETS_TRASH: '/{messageBoxId}/tickets/trash/p1',
  TICKETS_MISSED_CALL: '/{messageBoxId}/tickets/missed-call/p1',
  TICKETS_VOICEMAIL: '/{messageBoxId}/tickets/voicemail/p1',
  TICKETS_QUERY: '/{messageBoxId}/tickets/query/{queryId}/p1',
  TICKETS_LABEL: '/{messageBoxId}/tickets/label/{labelId}/p1',
  TICKETS_BROADCAST_ALL: '/{messageBoxId}/broadcasts/all/p1',
  TICKETS_BROADCAST_DRAFT: '/{messageBoxId}/broadcasts/draft/p1',
  TICKETS_BROADCAST_SCHEDULED: '/{messageBoxId}/broadcasts/scheduled/p1',
  TICKETS_BROADCAST_SENDING: '/{messageBoxId}/broadcasts/sending/p1',
  TICKETS_BROADCAST_SENT: '/{messageBoxId}/broadcasts/sent/p1',

  /* POPUP ROUTERS */
  CREATE_MAIL_POP_OUT: '/popout/mail/new?message_box_id={messageBoxId}',

  /* TICKET SETTINGS ROUTERS */
  TICKET_SETTINGS_INITIAL: '/tickets-setting/{messageBoxId}/settings/initial',
  TICKET_SETTINGS_TEMPLATE: '/tickets-setting/{messageBoxId}/settings/template/{categoryId}/{templateId}',
  TICKET_SETTINGS_PHRASE: '/tickets-setting/{messageBoxId}/settings/phrase/{categoryId}/{phraseId}',
  TICKET_SETTINGS_RULE: '/tickets-setting/{messageBoxId}/settings/rule/all',
  TICKET_SETTINGS_ROLE: '/tickets-setting/{messageBoxId}/settings/role',

  TICKET_SETTINGS_MAIL_RECEIVE: '/tickets-setting/{messageBoxId}/settings/mail/receive',
  TICKET_SETTINGS_MAIL_SEND: '/tickets-setting/{messageBoxId}/settings/mail/send',
  TICKET_SETTINGS_MAIL_COMPOSE: '/tickets-setting/{messageBoxId}/settings/mail/compose',
  TICKET_SETTINGS_MAIL_ATTACHMENT_URL: '/tickets-setting/{messageBoxId}/settings/mail/attachment-url',
  TICKET_SETTINGS_MAIL_AUTO_REPLY: '/tickets-setting/{messageBoxId}/settings/mail/auto-reply',
  TICKET_SETTINGS_MAIL_QUESTIONNAIRE: '/tickets-setting/{messageBoxId}/settings/mail/questionnaire',
  TICKET_SETTINGS_MAIL_SIGNATURE: '/tickets-setting/{messageBoxId}/settings/mail/signature',
  TICKET_SETTINGS_MAIL_USER_SIGNATURE: '/tickets-setting/{messageBoxId}/settings/mail/user-signature',
  TICKET_SETTINGS_CHAT_WIDGET: '/tickets-setting/{messageBoxId}/settings/chat-widget/{chatWidgetId}/basic',
  TICKET_SETTINGS_LINE: '/tickets-setting/{messageBoxId}/settings/line',
  TICKET_SETTINGS_CHAT_WORK: '/tickets-setting/{messageBoxId}/settings/chatwork',
  TICKET_SETTINGS_INSTAGRAM: '/tickets-setting/{messageBoxId}/settings/instagram',
  TICKET_SETTINGS_FACEBOOK: '/tickets-setting/{messageBoxId}/settings/facebook',
  TICKET_SETTINGS_CHAT_PLUS: '/tickets-setting/{messageBoxId}/settings/chatplus',
  TICKET_SETTINGS_RMS: '/tickets-setting/{messageBoxId}/settings/rms',
  TICKET_SETTINGS_YAHOO: '/tickets-setting/{messageBoxId}/settings/yahoo',
  TICKET_SETTINGS_SMS_MAX_MONTHLY_LIMIT: '/tickets-setting/{messageBoxId}/settings/sms/max-monthly-limit',
  TICKET_SETTINGS_BROADCAST_MAX_MONTHLY_LIMIT: '/tickets-setting/{messageBoxId}/settings/broadcast/max-monthly-limit',

  /* TICKET SETTINGS MESSAGE CONFIG ROUTERS */
  TICKET_SETTINGS_MESSAGE_CONFIG_BUSINESS_HOURS: '/tickets-setting/{messageBoxId}/settings/message-config/business-hours',
  TICKET_SETTINGS_MESSAGE_CONFIG_TICKET_LIST: '/tickets-setting/{messageBoxId}/settings/message-config/ticket-list',
  TICKET_SETTINGS_MESSAGE_CONFIG_LABEL: '/tickets-setting/{messageBoxId}/settings/message-config/label',
  TICKET_SETTINGS_MESSAGE_CONFIG_TICKET_CATEGORY: '/tickets-setting/{messageBoxId}/settings/message-config/ticket-category',
  TICKET_SETTINGS_MESSAGE_CONFIG_PENDING_REASON: '/tickets-setting/{messageBoxId}/settings/message-config/pending-reason',
  TICKET_SETTINGS_MESSAGE_CONFIG_SYSTEM_LINK: '/tickets-setting/{messageBoxId}/settings/message-config/system-link',
  TICKET_SETTINGS_MESSAGE_CONFIG_ANYFLOW_SYNC: '/tickets-setting/{messageBoxId}/settings/message-config/anyflow-sync',
  TICKET_SETTINGS_MESSAGE_CONFIG_SLACK: '/tickets-setting/{messageBoxId}/settings/message-config/slack',
  TICKET_SETTINGS_MESSAGE_CONFIG_CHATWORK: '/tickets-setting/{messageBoxId}/settings/message-config/chatwork',
  TICKET_SETTINGS_MESSAGE_CONFIG_TEAMS: '/tickets-setting/{messageBoxId}/settings/message-config/teams',
  TICKET_SETTINGS_MESSAGE_CONFIG_MESSAGE_EXPORTS: '/tickets-setting/{messageBoxId}/settings/message-config/message-export',

  /* SYSTEM ROUTERS */
  SYSTEM_MESSAGE_BOX_SETTINGS: '/system/message-box/message-box-setting',
  SYSTEM_CUSTOMER_GROUP: '/system/customer-group',
  SYSTEM_DASHBOARD: '/system/dashboard',
  SYSTEM_USER: '/system/user',
  SYSTEM_GROUP: '/system/group',
  SYSTEM_ROLE_CUSTOMIZATION: '/system/role-customization',
  SYSTEM_LOGIN_AUTH: '/system/login-auth/login',
  SYSTEM_AUDIT_LOG: '/system/audit-log',
  SYSTEM_IP_RESTRICTION: '/system/ip-restriction',
  SYSTEM_RISKY_URL_WARNING: '/system/risky-url-warning',
  SYSTEM_API_TOKEN: '/system/api-token',
  SYSTEM_CALL: '/system/call',
  SYSTEM_AGREEMENT_PLAN: '/system/agreement-plan',
  SYSTEM_USING_IP: '/system/using-ip',
};
